---
- name: Create guest user with ACL r-x permission on /opt and SSH key
  hosts: all
  become: true
  tasks:

    - name: Ensure user exists with specific password
      user:
        name: "{{ username }}"
        shell: /bin/bash
        password: "{{ user_password }}"
        create_home: yes
        state: present

    - name: Ensure .ssh directory exists
      file:
        path: "/home/{{ username }}/.ssh"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0700'

    - name: Add SSH public key
      copy:
        content: "{{ ssh_public_key }}"
        dest: "/home/{{ username }}/.ssh/authorized_keys"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0600'

    - name: Ensure ACL support (install acl package)
      package:
        name: acl
        state: present

    - name: Ensure /opt exists
      file:
        path: /opt
        state: directory

    - name: Grant r-x access to /opt using ACL for the user
      shell: "setfacl -m u:{{ username }}:rx /opt"
